[project]
name = "ai-stickers"
version = "0.0.0"

requires-python = "<3.13,>=3.10"

dependencies = [
    "telebot",
    "faster-whisper",
    "openai<1.0.0",
]

[tool.pdm.options]
add = ["--no-sync", "--no-self"]
update = ["--no-sync", "--no-self"]
remove = ["--no-sync", "--no-self"]
